---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-application
  labels:
    app: one-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: one-app
  template:
    metadata:
      labels:
        app: one-app
    spec:
      containers:
        - name: nginx
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
    
---
apiVersion: v1
kind: Service
metadata:
  name: one-app-service
spec:
  selector:
    app: one-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: one-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: app1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: one-app-service
                port: 
                  number: 80