Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "./confs" , "/confs_data"
  

  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |vb|
      vb.cpus = "1"
      vb.memory = "2048"
      vb.name = "master-node"
    end

    master.vm.provision "shell", path: "./scripts/server_init.sh"

  end


end