Vagrant.configure("2") do |config|

  config.vm.box = "generic/alpine318"
  config.vm.synced_folder "./confs" , "/confs_data"

  config.vm.define "master" do |master|
    master.vm.network  "private_network", ip: "192.168.56.110"
    master.vm.hostname = "Server"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus =  "1"
      vb.name = "master-node"  
    end

    master.vm.provision "shell", path: "./scripts/server_init.sh"

  end

  config.vm.define "slave" do |slave|
    slave.vm.network  "private_network", ip: "192.168.56.111"
    slave.vm.hostname = "slave-node"
    slave.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.name = "slave-node"
    end

    slave.vm.provision "shell", path: "./scripts/worker_init.sh"

  end

end